#!/usr/bin/env python3
"""Create original deterministic audiovisual control fixtures; needs Pillow/FFmpeg."""
import argparse
import hashlib
import json
import math
from pathlib import Path
import struct
import subprocess
import wave
from PIL import Image, ImageDraw

p = argparse.ArgumentParser(description=__doc__)
p.add_argument('output', type=Path)
a = p.parse_args()
a.output.mkdir(parents=True, exist_ok=True)
W, H = 1344, 768

def scene(x=300, subject='car'):
    image = Image.new('RGB', (W, H), '#e8f0f7')
    d = ImageDraw.Draw(image)
    d.rectangle((0, 450, W, H), fill='#bd9167')
    for y in range(475, H, 40):
        d.line((0, y, W, y), fill='#a77d57', width=2)
    d.polygon([(1050,440),(1120,405),(1190,440),(1120,478)], fill='#73b8fa')
    d.polygon([(1050,440),(1120,478),(1120,555),(1050,518)], fill='#2775c9')
    d.polygon([(1120,478),(1190,440),(1190,518),(1120,555)], fill='#1656a3')
    if subject == 'car':
        d.ellipse((x-125,550,x+145,584),fill='#99744f')
        d.rounded_rectangle((x-130,460,x+145,550),radius=25,fill='#d9383c')
        d.polygon([(x-75,465),(x-40,405),(x+65,405),(x+112,465)],fill='#de4545')
        d.polygon([(x-53,454),(x-28,418),(x+11,418),(x+11,454)],fill='#c4e8f1')
        d.polygon([(x+23,418),(x+57,418),(x+88,454),(x+23,454)],fill='#b1d9e7')
        for offset in (-78,88):
            d.ellipse((x+offset-30,520,x+offset+30,580),fill='#303b45')
            d.ellipse((x+offset-13,537,x+offset+13,563),fill='#c5cbd0')
    elif subject == 'boat':
        d.polygon([(250,510),(580,510),(495,590),(325,590)],fill='#f8f6e9')
        d.polygon([(410,505),(410,310),(565,505)],fill='#ffffff')
        d.line((410,310,410,520), fill='#685946',width=5)
    return image

scene(300).save(a.output/'first.png')
scene(850).save(a.output/'last.png')
scene(570).save(a.output/'reference-car.png')
scene(subject='cube').save(a.output/'reference-cube.png')
scene(subject='boat').save(a.output/'reference-boat.png')
with wave.open(str(a.output/'reference-audio.wav'),'wb') as f:
    f.setnchannels(2); f.setsampwidth(2); f.setframerate(32000)
    data = bytearray()
    for n in range(5*32000):
        t=n/32000
        phase=t%0.5
        env=math.exp(-phase*22)
        sample=int(6500*env*math.sin(2*math.pi*440*t))
        data.extend(struct.pack('<hh',sample,sample))
    f.writeframes(data)
cmd=['ffmpeg','-v','error','-f','rawvideo','-pix_fmt','rgb24','-s',f'{W}x{H}',
     '-r','24','-i','pipe:0','-an','-c:v','libx264','-preset','fast','-pix_fmt','yuv420p',
     str(a.output/'reference-silent.mp4')]
proc=subprocess.Popen(cmd,stdin=subprocess.PIPE)
for i in range(120):proc.stdin.write(scene(300+round(550*i/119)).tobytes())
proc.stdin.close()
if proc.wait():raise RuntimeError('fixture encoding failed')
subprocess.run(['ffmpeg','-v','error','-i',str(a.output/'reference-silent.mp4'),
                '-i',str(a.output/'reference-audio.wav'),'-c:v','copy','-c:a','aac',
                '-ar','32000','-ac','2','-shortest',str(a.output/'reference-sound.mp4')],check=True)
files=[]
for f in sorted(a.output.iterdir()):
    if f.name=='manifest.json':continue
    entry=dict(name=f.name,bytes=f.stat().st_size,sha256=hashlib.sha256(f.read_bytes()).hexdigest(),
               source='Original procedural test fixture generated by make_fixtures.py; no external media')
    if f.suffix in ('.wav','.mp4'):
        entry['probe']=json.loads(subprocess.check_output(['ffprobe','-v','error','-show_streams','-show_format','-of','json',str(f)]))
    files.append(entry)
(a.output/'manifest.json').write_text(json.dumps(files,indent=2)+'\n')
print(json.dumps([dict(name=x['name'],bytes=x['bytes']) for x in files],indent=2))
