apiVersion: v1
kind: Namespace
metadata:
  name: firecracker-lab
  labels:
    app.kubernetes.io/part-of: firecracker-lab
---
apiVersion: v1
kind: Pod
metadata:
  name: kata-fc-workbench
  namespace: firecracker-lab
  labels:
    app.kubernetes.io/name: kata-fc-workbench
spec:
  runtimeClassName: kata-fc-lab
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  containers:
    - name: workbench
      image: docker.io/library/nginx:1.20.1-alpine
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
        - |
          echo "runtimeclass=kata-fc-lab"
          echo "guest-kernel=$(uname -r)"
          echo "guest-machine=$(uname -m)"
          echo "guest-hostname=$(hostname)"
          ip address
          while true; do sleep 3600; done
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: "1"
          memory: 256Mi
      volumeMounts:
        - name: scratch
          mountPath: /work
  volumes:
    - name: scratch
      emptyDir: {}
