apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: deepseek-v4-flash-vllm-lmcache-ab
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/aik8s.run~1experiment-mode
        value: lmcache-mp
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "true"
